theme: jekyll-theme-minimal
title: Tachyon Chasing Logs
description: For all the pets of the world, and all whose beck and call they heed.

defaults:
  - scope:
      path: ""
      type: years
    values:
      layout: year

years: [2025] # Add all years you have posts for
