title: tachyon chasing logs
theme: minima
plugins:
  - jekyll-feed
default_image: /assets/images/preview.png
future: true
  
years: [2025]  # Update with actual years
defaults:
  - scope:
      path: ""
    values:
      layout: default
      
collections:
  years:
    output: true
    permalink: /:path/
